### ISSUE TITLE
Installation instructions lead to install with multiple cucumber versions

### ISSUE THREAD

**Issue by tuna-rootnet** [Marketionist/testcafe-cucumber-steps#112]
I'm attempting to add testing with testcafe to my project. I followed the instructions on https://www.npmjs.com/package/testcafe-cucumber-steps, but always get this error:

```
$: node_modules/.bin/gherkin-testcafe
⠸

Page Objects from PO_FOLDER_PATH: 
{
    "test-page-example": {
        "linkAbout": "a[href*=\"about.google\"]",
        "header": ".header",
        "linkOurProducts": ".header a[title=\"Our products\"]"
    }
}

ERROR Cannot prepare tests due to the following error:
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at getDefinitionLineAndUri (~/testcafe-test/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:184:27)
    at buildStepDefinitionConfig (~/testcafe-test/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:124:7)
    at SupportCodeLibraryBuilder.Given [as defineStep] (~/testcafe-test/node_modules/cucumber/lib/support_code_library_builder/index.js:51:79)
    at Object.<anonymous> (~/testcafe-test/node_modules/testcafe-cucumber-steps/index.js:153:1)
    at ~/testcafe-test/node_modules/gherkin-testcafe/src/compiler.js:244:26
    at ~/testcafe-test/node_modules/gherkin-testcafe/src/compiler.js:243:17
    at GherkinTestcafeCompiler._loadStepDefinitions (~/testcafe-test/node_modules/gherkin-testcafe/src/compiler.js:248:5)
    at GherkinTestcafeCompiler.getTests (~/testcafe-test/node_modules/gherkin-testcafe/src/compiler.js:143:5)

```
Googling the error tells me this is due to a double dependency on cucumber. For the life of me, I can't figure out how to fix it. I did narrow it down (I think) to installing `testcafe-cucumber-steps`; if I install the other packages and then try to run a basic feature file, I just get an error saying the step is missing, which makes sense.

So, if I follow the instructions but _don't_ install `testcafe-cucumber-steps` immediately, I get this:
```bash
npm init --yes
npm install @cucumber/cucumber testcafe gherkin-testcafe --save-dev
```
The package.json is created, and the only version in the lockfile is 7.x. Add a featurefile to check if gherkin works at this point and run it, and you get the error of a missing step:
```
Feature: Landing page tests
    As u user of Application
    I should be able to use landing page
    to see the title

Scenario: Open the landing page, page title should be present
    Given user goes to URL "http://foo.com"
    Then the title should be "bar"
```
```
$: node_modules/.bin/gherkin-testcafe firefox
 Running tests in:
 - Firefox 90.0 / Linux 0.0

 Feature: Landing page tests
 ✖ Scenario: Open the landing page, page title should be present

   1) Error: Step implementation missing for: user goes to URL "http://foo.com"

      Browser: Firefox 90.0 / Linux 0.0

         262 |      if (isMatched) {
         263 |        return this._runStep(stepDefinition.code, testController, parameters, table, docString);
         264 |      }
         265 |    }
         266 |
       > 267 |    throw new Error(`Step implementation missing for: ${step.text}`);
         268 |  }
         269 |
         270 |  _runStep(step, testController, parameters, table, docString) {
         271 |    const markedFn = testRunTracker.addTrackingMarkerToFunction(testController.testRun.id, step);
         272 |

         at GherkinTestcafeCompiler._resolveAndRunStepDefinition (~/testcafe-test/node_modules/gherkin-testcafe/src/compiler.js:267:11)
         at <anonymous> (~/testcafe-test/node_modules/gherkin-testcafe/src/compiler.js:179:28)

```
Next, I add `testcafe-cucumber-steps`
```
$: npm install testcafe-cucumber-steps --save-dev

npm WARN deprecated cucumber@6.0.5: The npm package has moved to @cucumber/cucumber

added 22 packages, and audited 520 packages in 3s

27 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Which strikes me as odd, because now you get a warning of 6.0.5 being installed as well and is deprecated. Next, run the prepare script and then run my feature file or the prepared one again, and it results in the `ERR_INVALID_ARG_TYPE` error from above.

I have no idea what I'm doing wrong here. If I don't install the testcafe-cucumber-steps but copy/paste a couple of given/then steps from node_modules/testcafe-cucumber-steps/index.js to a file of my own, it works like a charm. I'd really rather not have my own copy of the steps, though. The package seems pretty cool in defining them all for me.

How do I fix this?

**Comment by Marketionist** [comment]
Hello @tuna-rootnet, thanks for reaching out! I just reproduced your issue while installing all dependencies:
```
npm init --yes
npm install @cucumber/cucumber testcafe gherkin-testcafe testcafe-cucumber-steps --save-dev
node node_modules/testcafe-cucumber-steps/utils/prepare.js
```
and then running tests with:
```
node_modules/.bin/testcafe
```

But if the tests are triggered with:
```
node_modules/.bin/gherkin-testcafe
```
it tends to work ok. Please double check if that will work for you.

**Comment by tuna-rootnet** [comment]
Thanks for you reply! I've tried both ways of starting the tests, and they both end up at the same error. The `gherkin-testcafe` way of running them gives a slightly longer stack, but they both end with this:
```
ERROR Cannot prepare tests due to the following error:
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at getDefinitionLineAndUri (~/testcafe-test/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:184:27)
    at buildStepDefinitionConfig (~/testcafe-test/node_modules/cucumber/lib/support_code_library_builder/build_helpers.js:124:7)
    at SupportCodeLibraryBuilder.Given [as defineStep] (~/testcafe-test/node_modules/cucumber/lib/support_code_library_builder/index.js:51:79)
    at Object.<anonymous> (~/testcafe-test/node_modules/testcafe-cucumber-steps/index.js:153:1)
```
I though maybe `cucumber` was installed globally somewhere, but running `npm list -g --depth 0` tells me I only have `npm` and `n` global.

Do you have any other ideas?

**Comment by tuna-rootnet** [comment]
Quick follow up: if I change try/catch at the beginning of testcafe-cucumber-steps/index.js to try  `Given = require('@cucumber/cucumber').Given` first and fall back to `cucumber`, it works.

**Comment by Marketionist** [comment]
@tuna-rootnet I just rolled out a version with updated import - please update `testcafe-cucumber-steps` to `1.20.1` and let me know if that fixes the issue on your side.

**Comment by tuna-rootnet** [comment]
Yes, this works! Thank you very much!

**Comment by Marketionist** [comment]
Happy to help!

**Comment by vcardins** [comment]
I'm using the `1.20.1` version but still getting the error. Any ideas?
