### ISSUE TITLE
package.json update needed: Cucumber is nowadays publishing new releases to @cucumber/cucumber - not cucumber

### ISSUE THREAD

**Issue by esaruoho** [Marketionist/testcafe-cucumber-steps#122]
hi @Marketionist

```
Cucumber is publishing new releases under @cucumber/cucumber
```

so the package.json reference of cucumber no longer works.

**Comment by Marketionist** [comment]
@esaruoho as you can see in https://github.com/Marketionist/testcafe-cucumber-steps/blob/master/index.js#L16 we are checking for both `cucumber` and `@cucumber/cucumber` for the sake of backwards compatibility. This way consumers who have old versions of `cucumber` can still use this package along with the ones who have `@cucumber/cucumber`.

**Comment by esaruoho** [comment]
Ok, closing :)
