### ISSUE TITLE
Need a way to create new custom steps to include into the provided set outside the project

### ISSUE THREAD

**Issue by pepesan** [Marketionist/testcafe-cucumber-steps#125]
We have found this project and it's awesome, very useful. The set of provided steps is very large, but is interesting to add new custom steps outside the library.

How we can add custom steps to a project that uses this library?

I've tried to add a js file under the rule  the test/**/*.js only with the step definition, but fails to load the step

But if I add manually to the main index.js of step definition works perfectly.

Any idea?

Best regard!
David

**Comment by Marketionist** [comment]
Paths to all step definitions and tests should be specified inside `.testcaferc.json` configuration file in an array in `src`:
```
"src": ["node_modules/testcafe-cucumber-steps/index.js", "tests/**/*.js", "tests/**/*.feature"],
```
