### ISSUE TITLE
Access the page objects from custom steps

### ISSUE THREAD

**Issue by Mekebra** [Marketionist/testcafe-cucumber-steps#130]
Seems to be a miss that one can't access the page objects

**Comment by Marketionist** [comment]
Thanks for pointing this out @Mekebra!

I just released an update to address this in https://github.com/Marketionist/testcafe-cucumber-steps/pull/132. If you want to get access to Page Objects in your custom Cucumber steps - you can just require them inside any step definitions
file like this:
```javascript
const pageObjects = require('testcafe-cucumber-steps/utils/get-page-objects.js');
```

Please upgrade to testcafe-cucumber-steps `1.21.0` and let me know if it works ok for you.

**Comment by Marketionist** [comment]
Closing this issue, @Mekebra please feel free to reopen if needed.
